version: 1.0.0.{build}
before_build:
- cmd: nuget restore
configuration: Release
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal

after_build:
- cmd: >-
    cd packages\Tools.InnoSetup.5.5.6\tools
    
    iscc "..\..\..\install.iss"

artifacts: 
- path: Installator

deploy:
- provider: GitHub
  release: Designer-v$(appveyor_build_version)
  auth_token:
    secure: 4jp/ql+5OgPXpxhTLqrZhRFXF3jvQ65SGptXrvZ4NIVIoX29OKd5FAZC95PABJW0
  on:
    configuration: Release
    branch: master